### ISSUE TITLE
Methode de mise à jour du nombre de chiffre Max

### ISSUE THREAD

**Issue by Egendron** [Habib-Bah/Projet3#3]
Pour setter ta valeur min et ta valeur max tu utilise un switch avec 9 cas et un default.
Essaie de trouver une autre facon de faire en utilisant des mathematiques.
Indice: tu as besoin des operateurs '/' et '%'.
Interet :

- Ton code sera plus simple. 
- Tu n'auras plus de problèmes pour un e taille max superieure à 9 ( en voyant le code,je suppose qu'actuellement cela ne fonctionne pas)

Fonction  : Configuration#MiseAJourDesValeurs

**Comment by Habib-Bah** [comment]
Bonjour,
J'ai corrigé le bug sur la mise à jour des valeurs min et max, désormais je n'ai plus de min.
J'ai aussi corrigé le fait que si l'on échange des lignes dans le fichier de configuration, que cela crée un bug.
